const e = {

      authPayLoads: null,
      isAuthEntity: false,
      authEntity: null,
      active: true,
      deleted: false,
      _id: "5e8c0021580572022e396336",
      properties: [
        {
          _id: "",
          isHash: false,
          isImage: false,
          isRichText: false,
          name: "title",
          htmlElement: "",
          type: "String",
          hasRelationShip: false,
          ref: {
            columnNameToDisplay: "",
            entityName: "",
            columnNameAsValue: "",
          },
          commonProperty: {
            required: { type: 0, default: false },
            default: { type: 1, default: "" },
            select: { type: 0, default: false },
            alias: { type: 1, default: "" },
          },
          indexProperty: {
            index: { type: 0, default: false },
            unique: { type: 0, default: false },
            sparse: { type: 0, default: false },
          },
          specificProperty: {
            minlength: { type: 1, default: "" },
            maxlength: { type: 1, default: "" },
            lowercase: { type: 0, default: false },
            uppercase: { type: 0, default: false },
            trim: { type: 0, default: false },
            match: { type: 0, default: false },
          },
        },
        {
          _id: "",
          isHash: false,
          isImage: true,
          isRichText: false,
          name: "image",
          htmlElement: "",
          type: "Array",
          hasRelationShip: false,
          ref: {
            columnNameToDisplay: "",
            entityName: "",
            columnNameAsValue: "",
          },
          commonProperty: {
            required: { type: 0, default: false },
            default: { type: 1, default: "" },
            select: { type: 0, default: false },
            alias: { type: 1, default: "" },
          },
          indexProperty: {
            index: { type: 0, default: false },
            unique: { type: 0, default: false },
            sparse: { type: 0, default: false },
          },
          specificProperty: {
            minlength: { type: 1, default: "" },
            maxlength: { type: 1, default: "" },
            lowercase: { type: 0, default: false },
            uppercase: { type: 0, default: false },
            trim: { type: 0, default: false },
            match: { type: 0, default: false },
          },
        },
        {
          _id: "",
          isHash: false,
          isImage: false,
          isRichText: false,
          name: "slidertypr",
          htmlElement: "",
          type: "ObjectId",
          hasRelationShip: true,
          ref: {
            columnNameToDisplay: "name",
            entityName: "slidertype",
            columnNameAsValue: "_id",
          },
          commonProperty: {
            required: { type: 0, default: false },
            default: { type: 1, default: "" },
            select: { type: 0, default: false },
            alias: { type: 1, default: "" },
          },
          indexProperty: {
            index: { type: 0, default: false },
            unique: { type: 0, default: false },
            sparse: { type: 0, default: false },
          },
          specificProperty: {
            minlength: { type: 1, default: "" },
            maxlength: { type: 1, default: "" },
            lowercase: { type: 0, default: false },
            uppercase: { type: 0, default: false },
            trim: { type: 0, default: false },
            match: { type: 0, default: false },
          },
        },
        {
          _id: "",
          isHash: false,
          isImage: false,
          isRichText: false,
          name: "action",
          htmlElement: "",
          type: "String",
          hasRelationShip: false,
          ref: {
            columnNameToDisplay: "",
            entityName: "",
            columnNameAsValue: "",
          },
          commonProperty: {
            required: { type: 0, default: false },
            default: { type: 1, default: "" },
            select: { type: 0, default: false },
            alias: { type: 1, default: "" },
          },
          indexProperty: {
            index: { type: 0, default: false },
            unique: { type: 0, default: false },
            sparse: { type: 0, default: false },
          },
          specificProperty: {
            minlength: { type: 1, default: "" },
            maxlength: { type: 1, default: "" },
            lowercase: { type: 0, default: false },
            uppercase: { type: 0, default: false },
            trim: { type: 0, default: false },
            match: { type: 0, default: false },
          },
        },
      ],
      name: "slider",
      entitySchema: {
        title: { type: "String" },
        image: { type: "Array" },
        slidertypr: { ref: "slidertype", type: "ObjectId" },
        action: { type: "String" },
      },
      uId: "5e8099490c8308299619dea0",
      createdOn: "2020-04-07T04:22:57.702Z",
      __v: 0,
    }
  
;
const data = require("./src/index").ProcessController(e);

console.log(data);
